---
# handlers file for apache2-role
- name: start-apache #name must be similar to notify task
  service:
    name: apache2
    state: started

- name: restart-apache #name must be similar to notify task
  service:
    name: apache2
    state: restarted

